{"name": "Ошибка при логине курьера без пароля", "status": "failed", "statusDetails": {"message": "AssertionError: assert 504 == 400\n +  where 504 = <Response [504]>.status_code", "trace": "self = <tests.test_login_courier.TestLoginCourier object at 0x0000028D3F59D760>\nregister_new_courier_return_login_password_delete_courier = ['qhpcancqzr', 'jtzuvtpijl', 'brthetwvyf']\n\n    @pytest.mark.xfailed\n    @allure.title('Ошибка при логине курьера без пароля')\n    def test_login_courier_without_password(self, register_new_courier_return_login_password_delete_courier):\n        login, _, _ = register_new_courier_return_login_password_delete_courier\n        data = {\"login\": login}\n    \n        response = requests.post(f\"{url}/api/v1/courier/login\", json=data)\n    \n>       assert response.status_code == 400\nE       assert 504 == 400\nE        +  where 504 = <Response [504]>.status_code\n\ntests\\test_login_courier.py:37: AssertionError"}, "start": 1727617222002, "stop": 1727617282150, "uuid": "4987a34b-bad8-463a-a83c-b852492ec01f", "historyId": "0b4bb7c7863ffde14ddeb8e810efce61", "testCaseId": "0b4bb7c7863ffde14ddeb8e810efce61", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_without_password", "labels": [{"name": "tag", "value": "xfailed"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-NLCLIKN5"}, {"name": "thread", "value": "8244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}